name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: install libpcap-dev
      run: "sudo apt-get update && sudo apt-get install -y  libpcap-dev"
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Build
      #run: go build -v ./...
      run: |
        go get github.com/hsiafan/httpdump
        go build github.com/hsiafan/httpdump
        ls -l

    - name: Test
      run: |
        go test -v ./...
        pwd

    - name: Archive production artifacts
      uses: actions/upload-artifact@v1
      with:
        name: httpdump
        path: /home/runner/work/httpdump/httpdump/httpdump
